project:
  type: website
  output-dir: docs

website:
  title: "Rohan Alexander"
  site-url: "https://rohanalexander.com"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: "Events"
        menu: 
        - events-tdw.qmd
        - events-llms_colloquium.qmd
        - events-reproducibility.qmd
        - events-software.qmd
      - text: "Teaching"
        menu: 
        - teaching-data_science_foundations.qmd
        - teaching-ethics_and_ds.qmd
        - teaching-inf2178.qmd
        - teaching-history_of_statistics.qmd
        - teaching-sta302.qmd
        - teaching-modeling.qmd
        - teaching-nlp.qmd
        - teaching-sta304.qmd
        - teaching-inf312.qmd
      - text: "Misc"
        menu: 
        - href: bookshelf.qmd
        - text: "Blog"
          href: blog.html
        - href: recs.qmd
      - text: "CV"
        href: pdfs/cv-academic-Rohan_Alexander.pdf
      - icon: github
        href: https://github.com/RohanAlexander
      - icon: twitter
        href: https://twitter.com/RohanAlexander
      - icon: envelope
        href: "mailto:rohan.alexander@utoronto.ca"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: true
  