---
title: "Bookshelf"
---

Inspired by Patrick Collison's [version](https://patrickcollison.com/bookshelf), this is an incomplete (so far) list of the books that Monica and I own in Toronto. I've been a bit more liberal than Patrick and included a section on books that I've read and would like to own. If you have recommendations, then please [get in touch](mailto:rohan.alexander@utoronto.ca). I usually only buy books that I like, but books with a ⭐️are ones either Monica or I especially like.

## Academic

- Bryant, John, and Junni L. Zhang, 'Bayesian Demographic Estimation and Forecasting'.
- Chan, Ngai Hang, 'Time Series'.
- Clark, Greg, 'The Son Also Rises'.
- Duflo, Esther, 'Expérience, science et lutte contre la pauvreté'. *Monica 'borrowed' this from the Berkeley Demography library before Duflo won the Nobel and now we're not giving it back.*
- Foster, Ghani, Jarmin, Kreuter, Lane, 'Big Data and Social Science'.
- Francois Chollet with JJ Allaire, 'Deep Learning with R'.
- ⭐️Friedman H, Jerome, Robert Tibshirani, and Trevor Hastie, 'Elements of Statistical Learning'.
- ⭐️Gelman, Andrew  and Jennifer Hill, 'Data Analysis Using Regression and Multilevel Hierarchical Models'. *Ah, the money-maker! Thank you Gelman and Hill. I haven't properly studied this book, just read it as needed, but Monica's probably read it more than enough for both of us.*
- Gelman, Andrew, Jennifer Hill and Aki Vehtari, 'Regression and Other Stories'. 
- Gelman, Andrew, John Carlin, Hal Stern, David Dunson, Aki Vehtari and Donald Rubin, 'Bayesian Data Analysis'. *Known as the old testament in our household.*
- Girosi, Federico and Gary King, 'Demographic Forecasting'.
- Healy, Kieran, 'Data Visualization'.
- Imai, Kosuke, 'Quantitative Social Science'.
- ⭐️McElreath, Richard, 'Statistical Rethinking'. *Known as the new testament in our household.*
- McLean, Ian, 'Why Australia Prospered'.
- Neuman, Lawrence W, 'Social Research Methods'.
- Petty, William, John Graunt and Charles Henry Hull, 'The Economic Writings of Sir William Petty: Together with the observations upon the bills of mortality, more probably by Captain John Graunt'.
- ⭐️Pitman, Jim, 'Probability'. *Monica loves this book. We own multiple copies.*
- Preston, Samuel, Patrick Heuveline and Michel Guillot, 'Demography'.
- Salganik, Matthew, 'Bit by Bit: Social Research in the Digital Age'.
- Smith, David and Nathan Keyfitz, 'Mathematical Demography'.
- Stewart, James, 'Calculus'.
- Taddy, Matt, 'Business Data Science'.
- Wachter, Ken, 'Essential Demographic Methods'.
- Wakerly, Dannis, William Mengenhall, Richard Scheaffer, 'Mathematical Statistics with Applications'.
- ⭐️Wickham, Hadley, and Grolemund, Garrett, 'R for Data Science'. *Some people convert to Catholicism when they get married, I converted to R. But my knowledge was piecemeal and going through this book addressed that.*
- ⭐️Witten, Daniela, Gareth James, Robert Tibshirani, and Trevor Hastie, 'Introduction to Statistical Learning'. *Going through this with Peter taught me a lot including: 1) if you want to learn something then buy a physical copy of a textbook, get a partner and commit to weekly chapter reviews; 2) learn statistics from statisticians; and 3) statistics is awesome and I want to learn more. I always thought that I was terrible at it because econometrics never came easily to me, but now I realise that maybe the econometrics-approach isn't for me, but the statistics one is.*
- Wu, Changbao and Mary Thompson, 'Sampling Theory and Practice'.


## Non-fiction

- '150 Years of Stats Canada!'.
- Achatz, Grant  and Nick Kokonas, 'Life, on the Line'.
- ⭐️Agassi, Andre, 'Open'. *Tennis is incidental to the aspects that make this book great, so try it even if you don't particularly like the sport. I can't remember who recommended it -- seems like a Nick Crocker type of book?*
- Aslett, Don, 'Is There Life After Housework'. *Got given this at the Museum of Clean in Pocatello, Idaho. The museum was surprisingly good!*
- Carson, Anne, 'Autobiography of Red'. *Present from Dad.*
- Clemens, Mark, 'The Mountain'. *Present from Dad.*
- Clinton, Bill, 'My Life'.
- Crabb, Annabel, 'Stop At Nothing'. *This Turnbull bloke sounds like he'd be a great prime minister.*
- Dennison, CJ, 'Yesterday's Hobart Today'.  *Present from Helen.*
- Edwards, John, 'Keating: The Inside Story'.
- Elliot, Francis  and James Hanning, 'Cameron'. *I haven't yet come across a good David Cameron biography, but this one was interesting. Focused on pre-parliament period.*
- Gaskell, Elizabeth, 'The Life of Charlotte Brontë'.
- ⭐️Halberstam, David, 'The Best and the Brightest'. *I read Plato's Republic at an impressionable age and so I used to think that if we could just put the smart people in charge then the 'right' decisions would be made. This book cured me of that.*
- Holden, Anthony, 'King Charles III'.
- Humphrey, Luke, 'Hansons Half-Marathon Method'.
- Humphrey, Luke, 'Hansons Marathon Method'. *Bought this; followed this; ran my best marathon.*
- Johnson, E, Robert and Janet L Byron, 'Berkeley Walks'.
- Kelly, Paul, 'Triumph and Demise'. *Present from Dad.*
- Kudelka, 'Hobart'.
- Lawrence, TE, 'Seven Pillars of Wisdom'. *'Borrowed' from Dad.* .
- Lepore, Jill, 'If Then'. *I've never been so disappointed by a book. So much potential.*
- Levitt, Steven and Stephen Dubner, 'Freakonomics'.
- Love, David, 'Unfinished Business'.
- Marr, David, 'Political Animal'.
- McNamee, Thomas, 'Alice Waters and Chez Panisse'.
- Mears, Ashley, 'Very Important People'.
- Megalogenis, George, 'The Longest Decade'.
- Mitchell, M. Waldrop, 'The Dream Machine'.
- Moore, Charles, 'Margaret Thatcher'. *Present from Dad.*
- NT News, 'What a Croc: Legendary Front Pages From the NT News'. Present from Mark.
- Obama, Barack, 'A Promised Land'.
- Obama, Barack, 'Audacity of Hope'.
- Petzold, Charles, 'Code: The Hidden Language of Computer Hardware and Software'.
- Schlesinger, Arthur, 'A Thousand Days'.
- Simmons, Bill, 'The Book of Basketball'.
- Sorenson, Ted, 'Kennedy'.
- Stephanopoulos, George, 'All Too Human'. *I thought that politics was romantic until I read this book when I was 20.*
- Trump, Donald  and Tony Schwartz, 'The Art of the Deal'. *This book is terrible. Read that [NYT article](https://www.nytimes.com/interactive/2018/10/02/us/politics/donald-trump-tax-schemes-fred-trump.html) about how he really made his money instead.*
- Tucker, Ross and Jonathan Dugas, 'Runner's World: The Runner's Body'.
- ⭐️Vanhoenacker, Mark, 'Skyfaring'. *Read this on your next flight.*
- ⭐️Vaughan, Diane, 'The Challenger Launch Decision'. *One of the greatest non-fiction books ever.*
- Wormser, Baron, 'The Road Washes Out in Spring'. *Stayed at the author's house, so bought some of his books and particularly liked this one about how his family lived off the grid in New England. Liked it even better after living in Amherst for a while.*
- Z, Jay, 'Decoded'.


## Fiction

- Aesop, 'Fables'.
- Amis, Kingsley, 'Lucky Jim'.
- Amis, Kingsley, 'The Crime of the Century'.
- Bronte, Anne, 'Agnes Grey'.
- Bronte, Anne, 'The Tenant of Wildfell Hall'.
- Bronte, Charlotte, 'Jane Eyre'.
- Bronte, Charlotte, 'Shirley'.
- Bronte, Charlotte, 'The Professor'.
- Bronte, Charlotte, 'Villette'.
- Bronte, Emily, 'Wuthering Heights'.
- Camus, Albert, 'Le Chute'.
- Chaucer, Geoffrey, 'The Canterbury Tales'.
- Christie, Agatha, 'Approximately 1,000,000 different titles'.
- Crichton, Michael, 'The Andromeda Strain'.
- Davies, Robertson, 'The Rebel Angels'.
- DeWitt, Helen, 'Lightning Rods'.
- DeWitt, Helen, 'Some Trick'.
- ⭐️DeWitt, Helen, 'The Last Samurai'. *Nothing to do with the Tom Cruise movie.*
- Dickens, Charles, 'Oliver Twist'.
- Doyle, Arthur Conan, 'Various titles'.
- Eliot, George, 'Middlemarch'.
- Eugenides, Jeffrey, 'Middlesex'.
- Fitzgerald, Scott, 'Tender is the Night'.
- Flanagan, Richard, 'The Sound of One Hand Clapping'. *Present from Helen.*
- Fleming, Ian, 'Moonraker'.
- Fleming, Ian, 'On Her Majesty's Secret Service'.
- Galsworthy, 'The Silver Spoon and Passers By'.
- Galsworthy, 'The White Monkey and A Silent Wooing'.
- Galsworthy, John, 'The Man of Property'.
- Galsworthy, John, 'End of the Chapter'.
- Galsworthy, John, 'Swan Song'.
- Galsworthy, John, 'The Forsyth Saga'.
- Grisham, John, 'The Pelican Brief'.
- Hardy, Thomas, 'Tess of the D'Urbervilles'.
- Haruf, Kent, 'Plainsong'.
- Ishiguro, Kazuo, 'The Unconsoled'.
- le Carré, John, 'A Perfect Spy'. *Dad likes le Carré so I buy them when there's a nice edition.*
- Melchor, Fernanda, 'Hurricane Season'.
- Ondaatje, Michael, 'The English Patient'.
- Potok, Chaim, 'The Chosen'.
- Rowling, K, J, 'Harry Potter and the Half-Blood Prince'.
- Rushdie, Salman, 'The Moor's Last Sigh'.
- Schulz, Charles, 'Snoopy and the Red Baron'.
- Schulz, Charles, 'Very Funny, Charlie Brown'.
- Seth, Vikram, 'The Golden Gate'.
- Shakespeare, William, 'Complete Works'.
- Simson, Graeme, 'The Rosie Project'.
- Thackeray, William, 'Vanity Fair'.
- Tolstoy, Leo, 'War and Peace'.
- ⭐️Waugh, Evelyn, 'Brideshead Revisited'.
- Waugh, Evelyn, 'Officers and Gentlemen'.
- Winton, Tim, 'Cloudstreet'. *All Australians have a copy of this. I think it's in the constitution.*
- Winton, Tim, 'Island Home'. *Present from Helen. There may be a theme emerging.*
- Winton, Tim, 'The Shepherd's Hut'. *Present from Helen.*


## Cookbooks

- Alexander, Stephanie, 'The Cook's Companion'. *Again, all Australians own this.*
- Country Women's Association of Tasmania, 'The 21st Birthday Cookery Book'. *My understanding, based on Helen, is that all Tasmanian women own this.*
- Evans, Matthew, Nick Haddow and Ross O'Meara, 'The Gourmet Farmer Goes Fishing'. *Present from Helen.*
- Grossi, Guy, 'Italian'. *Present from Angela.*
- Keller, Thomas, 'Bouchon Bakery'.
- Oliver, Jamie, 'Jamie's 30-Minute Meals'.
- Pant, Pushpesh, 'India'.
- Redzepi, Rene and David Zilber, 'The Noma Guide to Fermentation'.
- Women's Weekly, 'Children's Birthday Cake Book'.


## Want to buy

- Carreyrou, John, 'Bad Blood: Secrets and Lies in a Silicon Valley Startup'. *About Theranos, a company that faked blood test results.*
- Chozick, Amy, 'Chasing Hillary'. *Extended 2016 Clinton campaign diary. Many (most?) campaign  dairies are terrible but this is worthwhile reading in and of itself and the interaction with 'Devil's Bargain' was especially good. See notes for 'Devil's Bargain'.*
- Green, Joshua, 'Devil's Bargain'. *About Bannon and his relationship with Trump. Worthwhile reading in and of itself, but the interaction with 'Chasing Hillary' was especially good. Neither is quantitative, but both help to understand 2016 e.g. how could the Comey reopening have a statistical effect? Green shows Bannon spent years creating specific mainstream doubts re Clinton. Chozick shows how/why Clinton campaign decisions accentuated them. I'm as keen on quant political analysis as anyone (shout out to @petitpoll if you want Australian polling!), but the snippets (and there was not much unfortunately) about each campaign's quant groups made me wonder if we have a cohort issue ATM. Specifically, do those in charge of political campaigns (or for that matter many businesses) know enough quant to know it's important, but not enough to appreciate, and hence be able to compensate for, it's weaknesses?*
- Ignatieff, Michael, 'Fire and Ashes: Success and Failure in Politics'. *Changed the way that I  thought about politics. Gave my copy to Amir.*
- Petzinger, Thomas, 'Hard Landing'. *About the deregulation of the US airline market.*
- Price A, David, 'The Pixar Touch'. *Incredible details about their overnight success, 23 years in the making.*
- Thiel, Peter, 'Zero to One'. *Maybe it's the jet-lag, but is this a business book that's actually not terrible? A few weak chapters, but enough interesting ones to outweigh them.*
- Yanighara, Hanya, 'A Little Life'. *Recommended by Lauren.*


## Best books that I read in:

* 2022
    - Kuang, R. F., 'Babel, or the Necessity of Violence'
    - Efron & Hastie, "Computer Age Statistical Inference" (🙏 Monica)
    - Light, Singer & Willett, "By Design"
    - Mindell, "Digital Apollo" (🙏 Dan)
    - Morange, "A History of Biology"
* 2021
    - Another baby was born in 2021.
* 2020
    - There was a pandemic.
* 2019
    - The baby was born in 2019.
* 2018: 
    - Carreyrou, John, 'Bad Blood'.
    - Green, Joshua, 'Devil's Bargain'.
    - Chozick, Amy, 'Chasing Hillary'.
    - Petzinger, Thomas, 'Hard Landing'.
    - Agassi, Andre, 'Open'.
    - DeWitt, Helen, 'Some Trick'.
    - Waldrop, Mitchell M, 'The Dream Machine'. 
    - Price, David A, 'The Pixar Touch'.
