---
title: "Colloquium on Applications of LLMs"
---

## Overview

The Data Sciences Institute is hosting a colloquium on applications of LLMs for faculty and students. This is an opportunity for researchers from different disciplines to exchange initial thoughts, experiences, and ideas, in a casual and informal setting, so that we can all better integrate LLMs into our research.

The event is happening on Tuesday, 11 April, 2023, at the Department of Statistical Sciences, University of Toronto. 

In-person attendance is encouraged, but there will be a Zoom option. To promote an open and honest exchange of preliminary ideas and impressions we won't record the event.

<!-- If you would like to attend, please register here: https://forms.gle/UQM8jyVpPePT1QbM8 -->

## Schedule

| Time | Event | Speaker | Perspective or topic |
| -- | --- | ----- | ----- |
| 09:00 | Coffee | - | - |
| 09:10 | Welcome | Mike Evans | Statistical Sciences  |
| 09:15 | Invited talk | Bree McEwan | Communication |
| 09:30 | Invited talk | Benjamin Haibe-Kains | Computational pharmacogenomics |
| 09:45 | Invited talk | Jason Hattrick-Simpers | Materials Science and Engineering |
| 10:00 | Invited talk | Marcel Fortin | Map and Data Library |
| 10:15 | Invited talk | Michael Hoffman | Computational genomics |
| 10:30 | Morning tea | - | - |
| 10:45 | Invited talk | Joshua Speagle, Kristen Menou, and Jo Bovy | Astrostatistics and Data Science; Physics and Astrophysics; Galactic Astrophysics | 
| 11:15 | Invited talk | Jonathan Rose | Electrical and Computer Engineering |
| 11:30 | Industry presentation | Edward Kim | Cohere |
| 11:45 | Invited talk | Wendy Wong | Political science |
| 12:00 | Masterclass | Jinyue Feng and Annie En-Shiun Lee | Computer Science. "An overview of how LLMs work" |
| 12:45 | Lunch break | - | - |
| 13:30 | Hands-on activity - Part I | - | Code your own GPT following https://youtu.be/kCc8FmEb1nY | 
| 14:30 | Afternoon tea | - | - |
| 14:45 | Hands-on activity - Part II | - | Code your own GPT following https://youtu.be/kCc8FmEb1nY |
| 16:00 | Finish | - | - |


## Contact

For any questions or comments, please contact Rohan Alexander: rohan.alexander@utoronto.ca.
