---
title: "Welcome!"
---

I am an assistant professor at the University of Toronto, jointly appointed in the [Faculty of Information](https://ischool.utoronto.ca/profile/rohan-alexander/) and the [Department of Statistical Sciences](https://www.statistics.utoronto.ca/people/directories/all-faculty/rohan-alexander). I am also the assistant director of [CANSSI Ontario](https://canssiontario.utoronto.ca), a senior fellow at [Massey College](https://www.masseycollege.ca), a faculty affiliate at the [Schwartz Reisman Institute for Technology and Society](https://sr-institute.utoronto.ca/), and a co-lead of the [DSI](https://datasciences.utoronto.ca) Thematic Program in Reproducibility.

My book on foundational data science, *[Telling Stories With Data](https://www.tellingstorieswithdata.com/)*, is expected to be published by Chapman and Hall/CRC in the second half of 2023. The central thesis of the book is that a revolution is needed in data science, and I propose a view of what it could look like.

My research investigates how we can develop workflows that improve the trustworthiness of data science. I am particularly interested in the role of testing in data science.

My teaching helps students from a wide range of backgrounds learn how to use data to tell convincing stories. I am an associate editor of the *Journal of Statistics and Data Science Education*.

I hold a PhD in Economics from the Australian National University where I focused on economic history and was supervised by [John Tang](https://sites.google.com/view/john-tang/home) (chair), [Martine Mariotti](https://researchers.anu.edu.au/researchers/mariotti-m), [Tim Hatton](https://researchers.anu.edu.au/researchers/hatton-tj), and [Zach Ward](https://sites.google.com/site/zachaward/).


I am married to [Monica Alexander](https://www.monicaalexander.com), and we have two young children.
