---
title: "Recommendations"
---

## Australia

**Brisbane**

- There are free BBQs available on Kangaroo Point cliffs---have an early dinner and watch the night close in.
- The Barra Boys.
- Pizza Caffe at the University of Queensland.
- Go for a run, starting at about the Southbank Ferry Terminal, then cross the Goodwill Bridge, then either left for a shorter run (cross back on Kurilpa Bridge) or right and stick along the river and keep going until you get too tired---making it to Sydney Street Ferry Terminal is great, but even better to try to get to New Farm Park Ferry Terminal---then get a City Cat back to Southbank. That will end up about 10-12km depending on specifics.
- Hire a car and drive an hour north to Moffat Beach (not patrolled) or Dicky Beach (patrolled). (Train + bus works also.)

**Canberra**

- The Cupping Room
- Rizla
- Volstead Repeal
- A run from Civic down to the lake, and ideally making it across both bridges is pretty great. Will end up at about 8-10km depending on where you're leaving from in Civic.

**Melbourne**

- Patricia Coffee Brewers (standing room only)
- Flora Indian Restaurant (cheap but great)
- Brunetti
- You can book a meeting room at the State library if you're a member (free to join)

**Sydney**

- Campos Coffee Newtown - get an affogato
- Circular Quay to Manly Ferry - get the commuter one, not the "fast" 
- NB: "Central" station isn't actually that central---you'll likely want Wynyard.

## Canada

**Toronto**

- California Sandwiches - 244 Claremont St.
- [Good Egg](https://goodegg.ca)---a book shop in Kensington Market that is focused on kitchen books. It sounds niche, and it is, but it's also great. (HT: Ryan Briggs)
- Vietnam Lovely Noodle - 378 Bloor St W.
- [Evangeline Toronto](https://www.evangelinetoronto.com) - 51 Camden St
  - This is a bar on Level 14 of the Ace Hotel. Go early on a nice evening and try for the outside table around the corner for a great view.
- Tap Phong -  360 Spadina Ave - in Chinatown provides an incredible selection of kitchen supplies at decent prices. Again, sounds weird, but it's a Toronto institution.
  

## UK

**Oxford**

- You can get inexpensive access to the Bodleian Libraries with a 'Reader' [application](https://www.bodleian.ox.ac.uk/join-the-libraries/apply).


