---
title: "On work-life balance"
description: |
  Some thoughts on work-life balance as a PhD student and junior faculty and how that changes over time. A talk delivered to the University of Toronto Faculty of Information 'How to get a PhD' session on work-life balance.
author:
  - name: Rohan Alexander
    url:
      rohanalexander.com: {}
date: 2021-05-04
thanks: "test"
preview: were_all_just_fingerpainting.png
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
draft: false
collections:
  posts:
    citations: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Introduction 

Hi, my name is Rohan Alexander. I'm an assistant professor at the University of Toronto, in the Faculty of Information, and the Department of Statistical Sciences. I'd like to thank Tony Tang for the invitation to talk about work-life balance.

The work-life balance that I'm going to talk about today is just something for me, right now. So maybe some of what I'll talk about will be relevant for you, but maybe my balance won't be, and that's okay. My main take-away, in any case, is that you're smart enough to work out what works for you.

I don't think there's only one optimal work-life balance, and if there is one, then it certainly changes over time. While doing my PhD, and also my wife doing her PhD, and us both now in faculty jobs, we've had a variety of opportunities to experience a bunch of different approaches to all this.  We've also now got a two-year-old and another on the way, so I've reflected on all this to come up with a few lessons that I'd like to share.

## Lessons

### Lesson 1: You're smart enough to work out what works for you

The first lesson is that you're smart enough to work out what works for you. When my first child was born, it was all a bit challenging. As folks who have done or are doing a PhD, we're trained in, and selected for, certain attributes, and none of those have any relation to your ability to care for an infant when it's 3am and you've not slept, and the child won't eat. I did what I was trained to do, which was look at the literature, synthesize it, plan, and execute. And of course, that didn't help.

One of my PhD supervisors had also had a challenging time around the birth of her children, and she emailed me, and she said, 'you're smart enough to work out what works for you'. And that's the key bit. You're here. The admissions committee doesn't make mistakes.

Today is all about us giving you advice, but in the end you're smart enough to work out what work-life balance works for you.

### Lesson 2: Ignore what everyone else says and does

The second lesson is to ignore what everyone else is saying. Our friend once said on Twitter there are two types of people: one type says they work all the time, and the other type say they never work. The takeaway is that both types of people are probably exaggerating, and you probably shouldn't believe either of them. Instead, you need to think about your own circumstances and decide what balance makes sense. And you need to recognize that will change as your circumstances change.

I've always been a morning person, so during my PhD I used to get up at 6am to start work and then stop in mid-afternoon and go for a run and then cook dinner early and then maybe do some lighter work in the evening. And I got good at working for long chunks of time. Then the baby arrived. I became a night person for a while, then I became a bursts-of-work person for a while, now I'm back to being a morning person, but it's more of a 4am start to get a chunk of work done, and then various bursts-of-work, followed by a short morning chunk, and then very little in the afternoon, when I may need to look after him, depending on sleep, and then maybe another chunk at night if he goes down easily. 

Ignore what others are doing, and react to your own circumstances.

### Lesson 3: Doing a PhD is hard

The third lesson is that doing a PhD is really, really hard (and it's meant to be). The fundamental purpose of doing a PhD is to create new knowledge. Knowledge that literally no one in the world has. 

One way to think about it is that you're going to become the world champion in one tiny little aspect of the world. The days of Oxbridge gentlemen athletes winning Olympic medals are gone, and that's true also of easy PhDs. What's left for us is the stuff that takes a huge amount of effort. Recognizing that fact, and the implication that working really hard at this is what it's going to take, is crucial. 

The work-life balance that I experience in a university isn't, and cannot be, the work-life balance of those that I know outside of universities. This job is just really different. You have to be prepared for things to be hard, and to work hard, and try not to take it personally when things don't work out straight away. It's part of the process

### Lesson 4: An extra hour of work is almost always worthwhile

The fourth lesson builds on this and it's that putting an extra hour into your work is always worthwhile. The nature of our job—creating new research—means that there is always something to do. This is not a job where you lay 500 bricks in a day and then call it a day. I had a job like that once, briefly, and that job was hard. But when it was done, it was done. Our job—doing research—is not like that. There's always something else that you can do. And it's beneficial to do that thing today, because that way you can build on it tomorrow.

There's enormous compounding in academia. Awards, conference and journal acceptances tend to go to those who already have plenty of them. So how do you get that first one? It's just hard, but putting an extra hour in will almost always compound over time and be useful. The thing about compounding interest is that initially you don't notice any benefit, but after a few years there's an enormous difference.

#### Lesson 4.5: Until it isn't

However, there is a corollary to that fourth lesson, and that is: Until it isn't. The fourth and a half lesson, as it were. The temptation is to just spend more and more time working. And that's fine for a while, and is important to be able to do, from time to time. But it doesn't work for more than a month or two. 

But now we have a contradiction. On the one hand, I've just told you that there's enormous benefits to compounding, and we all know about the importance of flow and staying in that state when you can achieve it. And on the other hand, if you take that to its natural conclusion and work all the time, you won't last in academia for long. So, what do we do? 

### Lesson 5: Use positive procrastination

This leads to the fifth lesson, which is that you use positive procrastination to your advantage. I wrote this talk when I was tired of writing my book, which I write when I'm tired of trying to write a paper. None of this is wasting time, but the task switching ensures a freshness and enthusiasm. Another advantage of positive procrastination when you're a PhD student is that it also helps you identify what you're passionate about.

Now you don't have to love what you do—plenty of professors don't—but I do and I'm going to speak now assuming this to be true, because it's gone part way to resolving this contradiction.

A friend once said that a way to think about passion is that it's your brain's way of tricking you into doing things that are boring or are hard. And if you can identify passion then it'll make your life a lot easier. When I started my PhD, I was in a bit of a malaise. I'd go from subject to subject, and certainly work at them, but not enjoy anything and there were a lot of long coffees with friends. I'd cycle home, and then at night and on the weekends, I'd spend my whole-time using R to do statistical analysis of political data in a reproducible way. Then during the day I'd go to university and go back to my malaise of not knowing what to do. Of course, with some support from various advisors and mentors, I eventually worked out that what I should be doing is using R to do statistical analysis of political data in a reproducible way for my PhD and after that everything got a lot easier! I loved what I was doing and work no longer felt like work.

There's a limit, of course, to positive procrastination. Because you need to make sure that you're shooting, and not just setting up shots, as it were. As a PhD student, you probably want to have about three projects, and that's about it. But I do think that cycling through, especially early in your PhD when it's easy to just email a professor and take a reading course to write a short paper, is something that more students should do and would help resolve work-life concerns. 

And again, the viability of this changes over your career. Now I have about 10-15 different projects because I supervise students, and I have some longer-term gambles that may or may not work out. However, because of how I have to work in fits and starts, I can't just do what I was trained to do, which is to throw more time into things. I need to try to be smarter about things and look for efficiencies and relationships between them.

### Lesson 6: Take complete, week/s-long breaks

And so we reach the sixth and final lesson, which is about having complete breaks, and I learnt this one from someone that I'll name, and that's Professor Kelly Lyons. Because once you've identified your passion and you understand the power of compounding and flow, it can be easy to just stay caught up in things. But to have an academic career or to finish a PhD without burning out, and if your work-life trick is going to be that you'd be doing what you get paid to do, even if you didn't get paid to do it, then you need to make sure that remains the case. 

Monica and I have started insisting on complete week-long breaks from time to time. Minimal computers, and no GitHub. And this is one aspect where having children certainly helps. Because they want all of your attention.


## We get to do what we want

Our work-life balance in academia is different to that of doctors, lawyers, and tech bros. We have the best job in the world. But our job is not like others. One of the great things about academia is the flexibility. We get to do whatever we want. 

That point bears repeating. We get to do whatever we want. And that means that whatever we're doing is something that we're choosing.

Hence, for me, it's become wrong to think that work and life are separate and that they need to be siloed. People outside of universities talk about work-life balance and the implication is that you need to make time for each. But in academia, that's not the way that I think of things. 

I think it's a spectrum. For some people, work is work, and life is life and they're completely separated, while for others all they do is work and that's their life. For most of us, we're probably somewhere in between. And I think that's especially the case in academia. Because you've got so much flexibility and ownership over what we do compared with, say, working at a bank. And so, in terms of work-life balance, it's about trying to work out what works for you. Thinking about what's important in your life and how that fits into your work. And also, being aware that this balance is going to change especially around life events such as having a baby, which will affect how you can work, as well as the volume. And that this change is good, appropriate, and normal, even if that's not recognized in the current academic structures.

If you enjoy coding, then taking a break from work might mean doing a fun coding project. If you enjoy hiking, then taking a break from work might mean going hiking. When my wife was doing her PhD, we went on road trips and worked in different environments. We did this because we loved our work, not because anyone was forcing us. We went to different cafes, and ate different foods, and ran in different parks, and went to different pubs, but for most of the day we sat at tables in random Airbnbs and worked. We have great memories of that, but not everyone wants to do that and that's okay.

Initially, your supervisor will put a huge amount of pressure on you, but I've found that as I've gotten older the person putting the most pressure on me is myself. Once you're at that stage, if you think 'oh I want a break, but I should get this done because the code isn't working, or I need to get it to my collaborator, or whatever', then chances are that it's okay and you should probably just email the collaborator to say that it'll be a week late and then take the week off. From time to time, I'll just declare a day off and not open the computer. If you think that maybe you don't have time for something, then you are probably right and you need to get out of it.

In grad school I've found that many people lose their hobbies. But maybe there is value in trying to make time, particularly for exercise. So, things like going for a run or being part of a team might be important for you. During my PhD a lot of my friends continued with rock-climbing, or cycling, or took up walking. 

## Between the ideal and the reality falls the shadow

Increasingly we see that the composition of academia is changing, for instance, in terms of the proportion of women in masters and PhD programs and junior faculty. However, institutional structures at all stages of academia are still fundamentally designed for people—particularly men—without caring responsibilities; and as such those who do not fit this mould often face enormous challenges

While things have changed, this structural issue has been increasingly brought to light during the pandemic. NSERC submission deadlines remained the same. NSERC grant application requirements remained the same. I said earlier that you should take a week off, but the amount of work to be done remains the same and NSERC doesn't change its deadlines just because you took a week off. Similarly, departments here didn't change their teaching, or service requirements. 

A lot of people with young children have not done any research for a year, and applied for few grants. Generalising from the literature on the effect of long-term job losses, chances are that, on average, our careers will not recover. And that's okay. We still get to do what we love. We might not become full professors, but being an associate would be great. It's still the best job in the world.

While I still think that it is correct to say, as I did above, that one shouldn't compare oneself to others, the fact remains that the academic structures do exactly that. If you are not of the type that academia is set-up for, then every day you will fail to measure up to those expectations. We are not in a normal job, and that's okay, but you need to recognize that the structures that job exists within may not be set-up for your circumstances. And it may be that these circumstances will dictate what can be accomplished, rather than your abilities.

## Concluding remarks

I don't think there's a one-size-fits-all for work-life balance. You need to work it out for yourself and part of that is just worrying about yourself, ignoring what others do or say they do. You're smart enough to work out what works for you, so just think. And once you work out what works for you, then set-out to make it easier for others.

I think that there's value in the struggle. Even if my cohort of academics with young children doesn't achieve what it may have, there's value in sticking with it, while that's possible. Next time, maybe some of us will be the ones who are chairs and NSERC reviewers. Even now, we have opportunities to make things easier for the next cohort, some of whom may be the undergrads that have spent the past year in Zoom classrooms. We have the best job in the world, and sometimes taking a step back and seeing it as bigger than oneself is important.

Thanks very much to Tony for giving me the opportunity to reflect on work-life balance at universities and how that changes over the life course, and I hope that he doesn't regret providing me with the platform too much. I'd be happy to take any questions.


## Acknowledgments {.appendix}

Thank you very much to Monica for reading a draft of this. Thank you also to John, Zach, Martine, Tim, and Jill at the ANU, and Kelly at U of T for helpful conversations about this topic at various points in time.