{
  "hash": "4d9f4eaa948247e85c5b06bde19cf2ae",
  "result": {
    "markdown": "---\ntitle: \"The average age of politicians in the Australian Federal Parliament (1901-2021)\"\ndescription: |\n  I examine the average age of politicians in the Australian Federal Parliament on a daily basis. Using a publicly available dataset I find that generally the Senate is older than the House of Representatives. The average age increased from Federation in 1901 through to 1949, when an expansion of the parliament's size likely brought many new politicians. I am unable to explain a sustained decline that occurred during the 1970s. From the 1980s onward there has been a gradual aging of both houses.\nauthor:\n  - name: Rohan Alexander\n    url: {rohanalexander.com}\ndate: 2021-12-02\noutput:\n  distill::distill_article:\n    self_contained: false\n    toc: true\n    toc_depth: 3\nbibliography: biblio.bib    \ndraft: false\ncollections:\n  posts:\n    citations: false\n---\n\n\n\n\n## Overview\n\nLast week I had the opportunity to attend my first thesis defence at a French-language institution (just to clarify - the actual defence was nonetheless conducted in English). Congratulations to Florence Vallée-Dubois on a successful defence. Her thesis looks at population ageing and democratic representation in Canada and is absolutely brilliant. \n\nHer work, and some earlier comments by Ben Readshaw, got me thinking about what the average age of a politician in Australia looks like. Thankfully, this is an example of a question that my new R package with Paul Hodgetts `AustralianPoliticians` makes easy to answer [@citeaustralianpoltiicaisn].\n\nThe average age of politicians in a parliament may have implications for the types of issues that are emphasised and the policies that are put in place. I examine the average age of Australian politicians in the Senate and the House of Representatives. In general, the Senate tends to be slightly older than the House of Representatives. I find a gradual increase in the average age from Federation through to the 1940s. In 1949 there was an expansion of the parliament and the average age noticeably declined. After a period of relative stability in the 1950s and 1960s, there was another noticeable decrease in the 1970s, followed by a gradual aging.\n\n\n\n\n## Data preparation\n\nThe dataset that I used in this note was primarily collected from records from the Australian Parliamentary Library, Wikipedia, and the Australian Dictionary of Biography. The dataset comprises biographical, political, and other information about every person elected to either the House of Representatives or the Senate. You can get the dataset in a series of CSVs on GitHub or as an R Package `AustralianPoliticians` available on CRAN.^[Monica Alexander uses an early version of this dataset to look at the average age of death of Australian politicians: https://www.monicaalexander.com/posts/2019-08-09-australian_politicians/.] \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"AustralianPoliticians\")\nlibrary(AustralianPoliticians)\nlibrary(lubridate)\nlibrary(tidyverse)\n```\n:::\n\n\nThe other packages that are required for the analysis are `lubridate` [@citeLubridate], the `tidyverse` [@citeTidyverse]. Additionally this note draws on the `knitr` [@citeKnitr] and `distill` [@citedistill] packages. All analysis is conducted in the statistical programming language R [@citeR]. \n\nI'm not going to spend a lot of time on descriptives about the dataset here because that's needed for a paper, and this is meant to be fun. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nall <- AustralianPoliticians::get_auspol(\"all\")\nhead(all)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 20\n  uniqueID   surname allOtherNames      firstName commonName\n  <chr>      <chr>   <chr>              <chr>     <chr>     \n1 Abbott1859 Abbott  Richard Hartley S… Richard   <NA>      \n2 Abbott1869 Abbott  Percy Phipps       Percy     <NA>      \n3 Abbott1877 Abbott  Macartney          Macartney Mac       \n4 Abbott1886 Abbott  Charles Lydiard A… Charles   Aubrey    \n5 Abbott1891 Abbott  Joseph Palmer      Joseph    <NA>      \n6 Abbott1957 Abbott  Anthony John       Anthony   Tony      \n# ℹ 15 more variables: displayName <chr>,\n#   earlierOrLaterNames <chr>, title <chr>, gender <chr>,\n#   birthDate <date>, birthYear <dbl>, birthPlace <chr>,\n#   deathDate <date>, member <dbl>, senator <dbl>,\n#   wasPrimeMinister <dbl>, wikidataID <chr>,\n#   wikipedia <chr>, adb <chr>, comments <chr>\n```\n:::\n\n```{.r .cell-code}\nall$member %>% table()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n.\n   0    1 \n 578 1205 \n```\n:::\n\n```{.r .cell-code}\nall$senator %>% table()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n.\n   0    1 \n1155  628 \n```\n:::\n:::\n\n\n\nBut briefly, there are 1,783 politicians in the dataset, with 1,205 having sat in the House of Representatives, which is the lower house, and 628 having sat in the Senate, which is the upper house. There is some overlap because there are people who sat in both houses.^[There are a handful of politicians who sat in the parliament, but were never elected - when the first parliament sat, there were initially some who were just appointed, and never went on to seek election. Conversely, there is one politician - Heather Hill - who was elected, but whose election was reversed before she could take her seat. While she never served in either house, she is included in the dataset for purposes of being able to link it to the elections dataset. However she is not included in the number of Australian politicians.]\n\nThe `AustralianPoliticians` package contains a number of datasets that are related by the `uniqueID` variable. This note requires the main dataset - 'all' - as well as two supporting datasets that provide more detailed information about the members - 'mps' - and the senators - 'senators'.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get the members and the dates they were in the house\nmps <- AustralianPoliticians::get_auspol(\"mps\")\n\naustralian_mps <- \n  all %>% \n  filter(member == 1) %>% \n  left_join(mps, \n            by = \"uniqueID\") %>% \n  select(uniqueID, mpFrom, mpTo) %>% \n  mutate(house = \"reps\") %>% \n  rename(from = mpFrom,\n         to = mpTo)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get the senators and the dates they were in the senate\nsenators <- AustralianPoliticians::get_auspol(\"senators\")\n\naustralian_senators <- \n  all %>% \n  filter(senator == 1) %>% \n  left_join(senators, \n            by = \"uniqueID\") %>% \n  select(uniqueID, senatorFrom, senatorTo) %>% \n  mutate(house = \"senate\") %>% \n  rename(from = senatorFrom,\n         to = senatorTo)\n\naustralian_politicians <- rbind(australian_mps, australian_senators)\nrm(australian_senators, australian_mps, mps, senators)\n\n# Change the names so that they print nicely in graphs/tables\naustralian_politicians <- \n  australian_politicians %>% \n  mutate(house =\n           case_when(\n             house == \"senate\" ~ \"Senate\",\n             house == \"reps\" ~ \"HoR\",\n             TRUE ~ \"OH NO\")\n         )\nhead(australian_politicians)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 4\n  uniqueID   from       to         house\n  <chr>      <date>     <date>     <chr>\n1 Abbott1869 1913-05-31 1919-11-03 HoR  \n2 Abbott1886 1925-11-14 1929-10-12 HoR  \n3 Abbott1886 1931-12-19 1937-03-28 HoR  \n4 Abbott1891 1940-09-21 1949-10-31 HoR  \n5 Abbott1957 1994-03-26 2019-05-18 HoR  \n6 Abel1939   1975-12-13 1977-11-10 HoR  \n```\n:::\n\n```{.r .cell-code}\n# australian_politicians$house %>% table()\n```\n:::\n\n\nFor each day, I would like to know the average age of everyone sitting in the parliament. There are a variety of ways to do this, but one is to create a dataset of two columns: `date` and `uniqueID.` Both of these are repeated, so that for every `date` there is every `uniqueID.` \n\n\n::: {.cell}\n\n```{.r .cell-code}\nstart_date <- ymd(\"1901-01-01\")\nend_date <- ymd(\"2021-12-31\")\n\npoliticians_by_date <- \n  tibble(\n    uniqueID = rep(australian_politicians$uniqueID %>% unique(),\n                   end_date - start_date + 1),\n    date = rep(seq.Date(start_date, end_date, by = \"day\"),\n               australian_politicians$uniqueID %>% unique() %>% length()\n               )\n    )\n\nhead(politicians_by_date)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 2\n  uniqueID   date      \n  <chr>      <date>    \n1 Abbott1869 1901-01-01\n2 Abbott1886 1901-01-02\n3 Abbott1891 1901-01-03\n4 Abbott1957 1901-01-04\n5 Abel1939   1901-01-05\n6 Adams1951  1901-01-06\n```\n:::\n:::\n\n\nAlthough the dataset is long at this point, it will be quite sparse as there are many combinations of `date` and `uniqueID` that are irrelevant. In the next step I check if each `uniqueID` was in parliament on each date, and filter away those that were not.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add an explicit end date to the uniqueIDs that are still in parliament and\n# hence have NA in the date they left parliament.\naustralian_politicians$to[is.na(australian_politicians$to)] <- end_date\n\npoliticians_by_date <- \n  politicians_by_date %>% \n  left_join(australian_politicians,\n            by = \"uniqueID\"\n            )\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in left_join(., australian_politicians, by = \"uniqueID\"): Detected an unexpected many-to-many relationship between\n`x` and `y`.\nℹ Row 1 of `x` matches multiple rows in `y`.\nℹ Row 1 of `y` matches multiple rows in `x`.\nℹ If a many-to-many relationship is expected, set\n  `relationship = \"many-to-many\"` to silence this warning.\n```\n:::\n\n```{.r .cell-code}\npoliticians_by_date <- \n  politicians_by_date %>% \n  mutate(in_parliament_interval = interval(from, to),\n         in_parliament_at_date = if_else(date %within% in_parliament_interval, \n                                         1, \n                                         0)\n         ) %>% \n  filter(in_parliament_at_date == 1) %>% \n  select(-in_parliament_interval,\n         -in_parliament_at_date,\n         -from,\n         -to)\n\nhead(politicians_by_date)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  uniqueID     date       house\n  <chr>        <date>     <chr>\n1 Bonython1848 1901-04-13 HoR  \n2 Braddon1829  1901-04-25 HoR  \n3 Brown1861    1901-05-11 HoR  \n4 Cameron1851  1901-06-13 HoR  \n5 Chanter1845  1901-07-13 HoR  \n6 Chapman1864  1901-07-14 HoR  \n```\n:::\n:::\n\n\nNow that the dataset is a bit more tractable, I add the birthday of every uniqueID and then calculate their age, in days, for every date.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoliticians_by_house_and_birthday <- \n  all %>% \n  select(uniqueID, birthDate, member, senator) %>% \n  pivot_longer(cols = c(member, senator), \n               names_to = \"house\", \n               values_to = \"in_it\"\n               ) %>% \n  filter(in_it == 1) %>% \n  select(-in_it) %>% \n  mutate(house = \n           case_when(\n             house == \"senator\" ~ \"Senate\",\n             house == \"member\" ~ \"HoR\",\n             TRUE ~ \"OH NO\")\n         )\n\n# Check if the catch-all has been invoked\n# politicians_by_house_and_birthday[politicians_by_house_and_birthday$house == \"OH NO\",]\n\npoliticians_by_date <- \n  politicians_by_date %>% \n  left_join(politicians_by_house_and_birthday,\n            by = c(\"uniqueID\", \"house\")\n            )\n\npoliticians_by_date <- \n  politicians_by_date %>% \n  filter(!is.na(birthDate)) %>% # I can't find Trish Wortley's birthday and also\n  # we don't know the birthdates of some of the politicians from around Federation.\n  mutate(age_as_at_that_date = date - birthDate)\n\nhead(politicians_by_date)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 5\n  uniqueID   date       house birthDate  age_as_at_that_date\n  <chr>      <date>     <chr> <date>     <drtn>             \n1 Bonython1… 1901-04-13 HoR   1848-10-15 19172 days         \n2 Braddon18… 1901-04-25 HoR   1829-06-11 26250 days         \n3 Brown1861  1901-05-11 HoR   1861-10-06 14461 days         \n4 Cameron18… 1901-06-13 HoR   1851-11-03 18119 days         \n5 Chanter18… 1901-07-13 HoR   1845-02-11 20605 days         \n6 Chapman18… 1901-07-14 HoR   1864-07-10 13517 days         \n```\n:::\n:::\n\n\nI need to work out the average age for each day. There are some politicians for whom we do not know their exact birthdate. Those have been removed in this calculation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naverage_age_by_date <- \n  politicians_by_date %>%\n  mutate(age_as_at_that_date = age_as_at_that_date / ddays(1)) %>% # This just converts it into a days count\n  group_by(date, house) %>% \n  summarise(average_age = median(age_as_at_that_date, na.rm = TRUE)) \n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`summarise()` has grouped output by 'date'. You can\noverride using the `.groups` argument.\n```\n:::\n\n```{.r .cell-code}\naverage_age_by_date <- \n  average_age_by_date %>% \n  mutate(average_age_in_years = average_age/365) \n\nhead(average_age_by_date)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 4\n# Groups:   date [3]\n  date       house  average_age average_age_in_years\n  <date>     <chr>        <dbl>                <dbl>\n1 1901-03-29 HoR         16765                  45.9\n2 1901-03-29 Senate      16086.                 44.1\n3 1901-03-30 HoR         17235                  47.2\n4 1901-03-30 Senate      18878.                 51.7\n5 1901-03-31 HoR         17236                  47.2\n6 1901-03-31 Senate      18878.                 51.7\n```\n:::\n:::\n\n\nI'll do the same thing except to work out the average by election period. This requires grabbing the election periods (there's an R package coming soon about this)!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nelections <- read_csv(\"https://raw.githubusercontent.com/RohanAlexander/australian_federal_elections/master/outputs/elections.csv\",\n                      col_types = \"Dicc\")\n\naverage_age_by_election <- \n  politicians_by_date %>%\n  left_join(elections %>% \n              rename(date = electionDate) %>% \n              select(-comment) %>% \n              mutate(house = \"HoR\"),\n            by = c(\"date\", \"house\")) %>% \n  ungroup() %>% \n  filter(house == \"HoR\") %>% \n  arrange(date, uniqueID) %>% \n  mutate(is_election = if_else(is.na(electionWinner), 0, 1),\n         is_election = if_else(is_election == lag(is_election, default = 0), 0, is_election),\n         election_counter = cumsum(is_election))\n\naverage_age_by_election <- \n  average_age_by_election %>%\n  ungroup() %>% \n  mutate(age_as_at_that_date = age_as_at_that_date / ddays(1)) %>% # This just \n  # converts it into a days count\n  group_by(election_counter) %>% \n  summarise(average_age = median(age_as_at_that_date, na.rm = TRUE),\n            first_date = min(date)) %>% \n  mutate(average_age_in_years = average_age/365) %>% \n  ungroup() \n```\n:::\n\n\n\n## Results\n\n### Over time\n\nThere are considerable changes over time (Figure \\@ref(fig:maingraph)).\n\n\n::: {.cell}\n\n```{.r .cell-code}\naverage_age_by_date %>% \n  # filter(year(date) == 1904) %>%\n  # filter(month(date) == 2) %>%\n  # filter(house == \"HoR\") %>%\n  ggplot(aes(x = date, y = average_age_in_years, colour = house)) +\n  geom_point(alpha = 0.5) +\n  labs(x = \"Date\",\n       y = \"Average age (years)\",\n       color = \"House\") +\n  theme_minimal() +\n  scale_color_brewer(palette = \"Set1\") \n```\n\n::: {.cell-output-display}\n![Average age in the Australian Federal Parliament on a daily basis](average_age_of_parliaments_files/figure-html/maingraph-1.png){width=672}\n:::\n:::\n\n\nI'll just separate each of the houses because there's a lot going on there (Figures \\@ref(fig:justrepsthings) and \\@ref(fig:justsenatethigns)).\n\n\n::: {.cell}\n\n```{.r .cell-code}\naverage_age_by_date %>% \n  filter(house == \"HoR\") %>% \n  ggplot(aes(x = date, y = average_age_in_years)) +\n  geom_point(alpha = 0.5, color = \"#F90000\") +\n  labs(x = \"Date\",\n       y = \"Average age (years)\") +\n  theme_minimal() +\n  scale_color_brewer(palette = \"Set1\") \n```\n\n::: {.cell-output-display}\n![Average age in the lower house on a daily basis](average_age_of_parliaments_files/figure-html/justrepsthings-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\naverage_age_by_date %>% \n  filter(house == \"Senate\") %>% \n  ggplot(aes(x = date, y = average_age_in_years)) +\n  geom_point(alpha = 0.5, color = \"#0080BD\") +\n  labs(x = \"Date\",\n       y = \"Average age (years)\") +\n  theme_minimal() +\n  scale_color_brewer(palette = \"Set1\") \n```\n\n::: {.cell-output-display}\n![Average age in the upper house on a daily basis](average_age_of_parliaments_files/figure-html/justsenatethigns-1.png){width=672}\n:::\n:::\n\n\n### Group by election period\n\nWe can also look at a summary of the results, averaged across days, on the basis of each election period (Table \\@ref(tab:maintable) and Figure \\@ref(fig:othergraph)).\n\n\n::: {.cell}\n\n```{.r .cell-code}\naverage_age_by_election %>% \n  select(-average_age) %>% \n  rename(`Election number` = election_counter,\n         `Period begins` = first_date,\n         `Average age (years)` = average_age_in_years) %>% \n  kable(caption = \"Average age by for each period between lower house elections\",\n        digits = 1,\n        booktabs = TRUE)\n```\n\n::: {.cell-output-display}\nTable: Average age by for each period between lower house elections\n\n| Election number|Period begins | Average age (years)|\n|---------------:|:-------------|-------------------:|\n|               1|1901-03-29    |                48.2|\n|               2|1903-12-16    |                48.8|\n|               3|1906-12-12    |                49.0|\n|               4|1910-04-13    |                50.1|\n|               5|1913-05-31    |                49.8|\n|               6|1914-09-05    |                51.9|\n|               7|1917-05-05    |                53.0|\n|               8|1919-12-13    |                52.2|\n|               9|1922-12-16    |                51.7|\n|              10|1925-11-14    |                52.3|\n|              11|1928-11-17    |                50.9|\n|              12|1929-10-12    |                49.4|\n|              13|1931-12-19    |                52.3|\n|              14|1934-09-15    |                51.1|\n|              15|1937-10-23    |                51.9|\n|              16|1940-09-21    |                52.2|\n|              17|1943-08-21    |                51.6|\n|              18|1946-09-28    |                53.3|\n|              19|1949-12-10    |                50.9|\n|              20|1951-04-28    |                52.4|\n|              21|1954-05-29    |                53.7|\n|              22|1955-12-10    |                52.4|\n|              23|1958-11-22    |                52.5|\n|              24|1961-12-09    |                53.5|\n|              25|1963-11-30    |                53.5|\n|              26|1966-11-26    |                52.5|\n|              27|1969-10-25    |                51.3|\n|              28|1972-12-02    |                49.5|\n|              29|1974-05-18    |                48.6|\n|              30|1975-12-13    |                47.1|\n|              31|1977-12-10    |                47.3|\n|              32|1980-10-18    |                48.3|\n|              33|1983-03-05    |                47.7|\n|              34|1984-12-01    |                48.2|\n|              35|1987-07-11    |                49.4|\n|              36|1990-03-24    |                48.5|\n|              37|1993-03-13    |                48.9|\n|              38|1996-03-02    |                48.9|\n|              39|1998-10-03    |                49.7|\n|              40|2001-11-10    |                50.7|\n|              41|2004-10-09    |                51.7|\n|              42|2007-11-24    |                51.2|\n|              43|2010-08-21    |                51.5|\n|              44|2013-09-07    |                50.0|\n|              45|2016-07-02    |                50.2|\n|              46|2019-05-18    |                51.7|\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\naverage_age_by_election %>% \n  ggplot(aes(x = first_date, y = average_age_in_years)) +\n  geom_point() +\n  labs(x = \"Date\",\n       y = \"Average age (years)\") +\n  theme_minimal() +\n  scale_color_brewer(palette = \"Set1\") \n```\n\n::: {.cell-output-display}\n![Average age in the Australian Federal Parliament, by election period](average_age_of_parliaments_files/figure-html/othergraph-1.png){width=672}\n:::\n:::\n\n\n\n\n### Compare with average age\n\nTo get a sense of whether the parliament is unusual we need know what is happening the broader population over this time. Fortunately, I know someone who is fairly handy when it comes to demography who can help.^[If you're interested in this sort of thing, then a PhD with [Monica Alexander](https://www.monicaalexander.com) is probably the way to go.]\n\nAlthough it's going to average over elections, which we've seen is a big source of variation, we can create an average age for each year, and then compare that against data from the Australian Bureau of Statistics (ABS). The ABS provides an estimate of historical population statistics in 3105.0.65.001 - Australian Historical Population Statistics, 2016, which was released in 2019. I want the second data cube - 2 - Population Age and Sex Structure - and within that I want Table 2.18 - Median age by sex, states and territories, 30 June, 1861 onwards.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(janitor)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'janitor'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    chisq.test, fisher.test\n```\n:::\n\n```{.r .cell-code}\nABS_data <- read_excel(\"3105065001ds0002_2019.xls\", \n                       sheet = \"Table 2.18\",\n                       skip = 4) %>%\n  janitor::clean_names() %>% \n  rename(area_and_type = x1,) %>% \n  select(-x1861, -x1870, -x1871, -x1881, -x1891)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nNew names:\n• `` -> `...1`\n```\n:::\n\n```{.r .cell-code}\nABS_data <- \n  ABS_data %>% \n  mutate(type = ifelse(area_and_type %in% c(\"Males\", \"Females\", \"Persons\"), area_and_type, NA),\n         area_and_type = ifelse(is.na(type), area_and_type, NA)) %>% \n  select(area_and_type, type, everything()) %>% \n  fill(area_and_type, .direction = \"down\") %>% \n  mutate(area_and_type = str_remove(area_and_type, \"\\\\(f\\\\)\\\\(g\\\\)\"))\n\nABS_data <- \n  ABS_data %>%  \n  filter(area_and_type == \"Australia\",\n         type == \"Persons\")\n\nABS_data <- \n  ABS_data %>%\n  pivot_longer(cols = starts_with(\"x\"),\n               names_to = \"year\",\n               values_to = \"median\") %>% \n  mutate(year = str_remove(year, \"x\"),\n         year = as.integer(year)) %>%\n  rename(area = area_and_type)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\naverage_age_by_year <- \n  politicians_by_date %>%\n  ungroup() %>% \n  mutate(year = year(date)) %>% \n  mutate(age_as_at_that_date = age_as_at_that_date / ddays(1)) %>% # This just \n  # converts it into a days count\n  group_by(year) %>% \n  summarise(average_age = median(age_as_at_that_date, na.rm = TRUE)) %>% \n  mutate(average_age_in_years = average_age/365) %>% \n  ungroup() \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\naverage_age_by_year %>% \n  left_join(ABS_data, by = \"year\") %>% \n  select(year, average_age_in_years, median) %>% \n  rename(Politicians = average_age_in_years,\n         Overall = median) %>% \n  pivot_longer(cols = c(Politicians, Overall), \n               names_to = \"population\",\n               values_to = \"median\") %>% \n  ggplot(aes(x = year, y = median, color = population)) +\n  geom_point() +\n  # geom_smooth() +\n  theme_classic() +\n  scale_color_brewer(palette = \"Set1\") +\n  labs(x = \"Year\",\n         y = \"Median age (years)\",\n         color = \"Population\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 23 rows containing missing values\n(`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](average_age_of_parliaments_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n\n\n## Concluding remarks\n\nI've had a brief look at the average age of politicians in the Australian Parliament. In general, I've found that they're older than the general population, and that there's a lot of variation.\n\nMore generally, I've shown one of the advantages of putting data onto GitHub, and wrapping that in an R Package where possible. If you don't like my analysis then you can grab the data yourself and play around with it!\n\nAs I mentioned at the top, [Florence Vallée-Dubois](https://florencevdubois.github.io) does a lot more of this type of work in her thesis 'Growing old : Population ageing and democratic representation in Canada' where she looks at 'whether the social changes brought about by population ageing also have implications for electoral politics and democratic representation.' There's probably a lot of similar work that could be done for Australia.\n\n\n\n\n\n\n\n\n\n## Acknowledgments {.appendix}\n\nThanks very much to Ben Readshaw and Florence Vallée-Dubois for motivating this note, and to Monica Alexander for her thoughtful comments.\n",
    "supporting": [
      "average_age_of_parliaments_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}